Repository GlueOps/cluster-monitoring, pull requests merged in 2024-10, with the labels that each got.

#39 Update and rename main.yaml to container_image.yaml
  .github/workflows/container_image.yaml
  .github/workflows/main.yaml
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#51 [skip actions] synced file(s) with internal-GlueOps/github-shared-files-sync
  .github/release.yml
Labels: Review effort [1-5]: 1, configuration changes, sync

#43 chore(deps): update python docker tag to v3.11.10
  Dockerfile
Labels: Review effort [1-5]: 1, patch, auto-update, include-in-release-notes, dependencies
